name: p4_qcml
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.*
  - pandas=2.*
  - pip
  - psycopg2
  - postgresql
  - pytest
  - python>=3.10
  - psi4
  - pytorch-cpu=2.5.1
  - jupyter
  - requests
  - setuptools
  - torchaudio
  - torchtriton
  - torchvision
  - pytorch_geometric
  - pytorch_scatter=2.1.2=cpu*
  - pytorch-minimize
  - matplotlib
  - pydantic=1,<2
  - scipy=1.15.*
  - tqdm
  - pip:
      - cdsg-tools
      - qm-tools-aw==1.4.5
      - qcmlforge==0.0.5
      - qcfractal==0.59
      - qcmanybody
      - qcfractalcompute==0.59
